CREATE TABLE IF NOT EXISTS AssignmentsStudents (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	AssignmentID INTEGER NOT NULL,
	StudentID INTEGER NOT NULL,
	AttemptedGrade INTEGER DEFAULT 0, 
	FOREIGN KEY(AssignmentID) REFERENCES Assignments(ID) ON DELETE CASCADE,
	FOREIGN KEY(StudentID) REFERENCES Students ON DELETE CASCADE
);