CREATE TABLE IF NOT EXISTS CoursesStudents (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CourseID INTEGER NOT NULL,
	StudentID INTEGER NOT NULL,
	FOREIGN KEY(CourseID) REFERENCES Courses(ID),
	FOREIGN KEY(StudentID) REFERENCES Students
);