CREATE TABLE IF NOT EXISTS CoursesStudents (
	ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	CourseID INTEGER NOT NULL,
	StudentID INTEGER NOT NULL,
	FOREIGN KEY(CourseID) REFERENCES Courses(ID) ON DELETE CASCADE,
	FOREIGN KEY(StudentID) REFERENCES Students(ID) ON DELETE CASCADE
);