CREATE TABLE IF NOT EXISTS students (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
	Gender INT NOT NULL,
	CourseID INTEGER,
	CreatedAt DATETIME,
	UpdatedAt DATETIME,
	FOREIGN KEY(CourseID) REFERENCES courses(ID)
);