CREATE TABLE IF NOT EXISTS Students (
    ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    FirstName VARCHAR(255) NOT NULL,
    LastName VARCHAR(255) NOT NULL,
	Gender INT NOT NULL,
	CreatedAt DATETIME,
	UpdatedAt DATETIME
);